import {
  AlertTriangle,
  BarChart3,
  Beef,
  BookMarked,
  BookOpen,
  Brain,
  Building2,
  Calendar,
  Check,
  CircleAlert,
  CircleCheck,
  CircleDot,
  ClipboardList,
  Cookie,
  Crown,
  Drama,
  Dumbbell,
  Flame,
  Gamepad2,
  Gem,
  Ghost,
  Goal,
  Hand,
  HelpCircle,
  Hourglass,
  Info,
  Landmark,
  Laugh,
  Leaf,
  Library,
  Lock,
  Megaphone,
  Menu,
  MessageCircle,
  Mic,
  Microscope,
  Newspaper,
  PartyPopper,
  Pointer,
  Radio,
  RefreshCw,
  Rocket,
  ScrollText,
  Search,
  Shirt,
  Siren,
  Smile,
  Sparkles,
  Star,
  Sun,
  Target,
  Timer,
  TrendingDown,
  TrendingUp,
  Trophy,
  Turtle,
  User,
  Vote,
  Waves,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/types/icons";

export const ICON_MAP: Record<IconName, LucideIcon> = {
  "alert-triangle": AlertTriangle,
  "bar-chart-3": BarChart3,
  beef: Beef,
  brain: Brain,
  "building-2": Building2,
  calendar: Calendar,
  check: Check,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  "clipboard-list": ClipboardList,
  cookie: Cookie,
  crown: Crown,
  drama: Drama,
  dumbbell: Dumbbell,
  flame: Flame,
  "gamepad-2": Gamepad2,
  gem: Gem,
  ghost: Ghost,
  goal: Goal,
  hand: Hand,
  "help-circle": HelpCircle,
  hourglass: Hourglass,
  info: Info,
  landmark: Landmark,
  laugh: Laugh,
  leaf: Leaf,
  library: Library,
  lock: Lock,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  mic: Mic,
  microscope: Microscope,
  menu: Menu,
  newspaper: Newspaper,
  "party-popper": PartyPopper,
  pointer: Pointer,
  radio: Radio,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  "scroll-text": ScrollText,
  search: Search,
  shirt: Shirt,
  siren: Siren,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  timer: Timer,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  trophy: Trophy,
  turtle: Turtle,
  user: User,
  vote: Vote,
  waves: Waves,
  x: X,
  zap: Zap,
  "book-open": BookOpen,
  "book-marked": BookMarked,
};
